In [15]:
# NumPy - Podstawowe Ćwiczenia
# Zbiór praktycznych zadań do nauki podstaw biblioteki NumPy.  

In [3]:
import numpy as np

In [4]:
# 1. Stwórz tablicę 10 zer

arr1 = np.zeros(10)
print("Tablica 10 zer: \n", arr1)

Tablica 10 zer: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# 2. Stwórz tablicę 10 jedynek
arr2 = np.ones(10)
print("Tablica 10 jedynek: \n", arr2)

Tablica 10 jedynek: 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
# 3️. Stwórz tablicę 10 piątek

arr_initial = np.ones(10)
arr3 = 5*arr_initial
print("Tablica 10 piątek: \n", arr3)

Tablica 10 piątek: 
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [8]:
# 4️. Stwórz tablicę z liczbami od 10 do 50

arr4 = np.arange(10,51)
print("Tablica 1-50: \n", arr4)

Tablica 1-50: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [9]:
# 5️. Stwórz tablicę z parzystych liczb od 10 do 50
arr5 = np.arange(10,51,2)
print("Tablica liczb parzystych z przedziału [10;50]: \n", arr5)

Tablica liczb parzystych z przedziału [10;50]: 
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [10]:
# 6️. Stwórz macierz 3x3 z wartościami od 0 do 8
arr_initial = np.arange(0,9)
arr6 = arr_initial.reshape(3,3)
print("Macierz 3x3 z wartościami 0-8: \n", arr6)

Macierz 3x3 z wartościami 0-8: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
# 7. Stwórz macierz jednostkową 5x5
arr7 = np.eye(5)
print("Macierz jednostkowa 5x5: \n", arr7)

Macierz jednostkowa 5x5: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
# 8. Wylosuj 10 liczb z rozkładu jednostajnego [0,1)

arr8 = np.random.rand(10)
print("10 losowych liczb z rozkładu jednostajnego [0,1): \n", arr8)

10 losowych liczb z rozkładu jednostajnego [0,1): 
 [0.29289608 0.28460251 0.57936465 0.47126702 0.32683653 0.45888549
 0.57570083 0.27080418 0.01708327 0.47801268]


In [13]:
# 9️. Wylosuj macierz 10x10 i znajdź jej wartości min i max

arr9 = np.random.rand(10,10)
print("Macierz losowych liczb z przedziału jednostajnego [0,1): \n", arr9)
print("Minimalna wartość w tej macierzy: ", arr9.min())
print("Maksymalna wartość w tej macierzy: ", arr9.max())

Macierz losowych liczb z przedziału jednostajnego [0,1): 
 [[0.63610335 0.48034202 0.52923772 0.25814612 0.66973152 0.88199477
  0.64039633 0.90728489 0.65122453 0.21522194]
 [0.95799463 0.10206099 0.91906748 0.82989911 0.36409259 0.71058079
  0.60247611 0.98104146 0.10515161 0.08986016]
 [0.66898409 0.96165822 0.86937013 0.587634   0.24394566 0.08521412
  0.71906939 0.78913283 0.82251058 0.96241131]
 [0.74288365 0.82520868 0.43694282 0.05616059 0.77114274 0.72383066
  0.37858339 0.18984569 0.35878665 0.03500281]
 [0.1257854  0.94831453 0.25813007 0.86817688 0.78484915 0.7365085
  0.63715084 0.09848312 0.01776849 0.07169669]
 [0.03485547 0.72598023 0.18805411 0.62184783 0.01133413 0.95022668
  0.39674592 0.89634447 0.77531532 0.6206761 ]
 [0.82317362 0.77690111 0.25689402 0.69124559 0.07146605 0.35114353
  0.88829131 0.48107911 0.98320286 0.90788043]
 [0.67494136 0.17651021 0.10100741 0.39045362 0.05535959 0.96322232
  0.87302229 0.48768123 0.91711667 0.90388994]
 [0.39151488 0.6569218

In [14]:
# 10. Stwórz tablicę 20 losowych liczb całkowitych 0–100 i znajdź ich średnią

arr10 = np.random.randint(0,101,20)
print("20 losowych liczb z przedziału [0,100]: \n", arr10)
print("Średnia z tych liczb: ", arr10.mean())

20 losowych liczb z przedziału [0,100]: 
 [85  2 97 40 70 74 51 71 39 38 25  5 53 17 43 75  1 43  9 49]
Średnia z tych liczb:  44.35


In [16]:
# 11. 

# Utwórz tablicę arr = np.arange(1, 21).
arr = np.arange(1,21)
print("Stworzona tablica: ", arr)

# Wypisz pierwsze 5 elementów
print("Pierwsze 5 elementów: ", arr[:5])

# Wypisz ostatnie 5 elementów
print("Ostatnie 5 elementów: ", arr[-5:])

# Wypisz tylko liczby parzyste
print("Parzyste elementy tablicy: ", arr[arr %2 == 0])

# Policz średnią, medianę i sumę wszystkich elementów
print("Średnia wszystkich elementów tablicy:  ", np.mean(arr))
print("Mediana wszystkich elementów tablicy:  ", np.median(arr))
print("Suma wszystkich elementów tablicy:  ", np.sum(arr))

Stworzona tablica:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Pierwsze 5 elementów:  [1 2 3 4 5]
Ostatnie 5 elementów:  [16 17 18 19 20]
Parzyste elementy tablicy:  [ 2  4  6  8 10 12 14 16 18 20]
Średnia wszystkich elementów tablicy:   10.5
Mediana wszystkich elementów tablicy:   10.5
Suma wszystkich elementów tablicy:   210


In [17]:
# 12. Operacje matematyczne

# Dla tej samej tablicy arr:
# Podnieś wszystkie liczby do kwadratu
arr_pow = arr**2
print("Nowa tablica: ", arr_pow)

# Policz pierwiastek kwadratowy każdego elementu
arr_root = np.sqrt(arr)
print("Po spierwiastkowaniu: ", arr_root)

# Oblicz log10 każdego elementu
arr_log = np.log10(arr)
print("Po zlogarytmowaniu: ", arr_log)

Nowa tablica:  [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]
Po spierwiastkowaniu:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595]
Po zlogarytmowaniu:  [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.         1.04139269 1.07918125
 1.11394335 1.14612804 1.17609126 1.20411998 1.23044892 1.25527251
 1.2787536  1.30103   ]


In [18]:
# 13. Losowe dane i indeksowanie

# Wygeneruj tablicę np.random.randint(0, 100, 15)
arr = np.random.randint(0,100,15) # Zauważ, że nie musisz już tego przekształcać za pomocą array(), bo to juz jest tablica
print("Wylosowana tablica: ", arr)

# Wypisz elementy większe niż 50
print("Elementy tablicy większe od 50: ", arr[arr>50])

# Zamień wszystkie elementy > 80 na 80
arr[arr > 80] = 80
print("Tablica po zmianie: ", arr)


# Znajdź indeks największej wartości (np.argmax)
print("Indeks o największej wartości w tablicy: ", np.argmax(arr))

Wylosowana tablica:  [12 17 87 82 73 77  3 74 41  9 62 12 10 77 35]
Elementy tablicy większe od 50:  [87 82 73 77 74 62 77]
Tablica po zmianie:  [12 17 80 80 73 77  3 74 41  9 62 12 10 77 35]
Indeks o największej wartości w tablicy:  2


In [19]:
''' 14. Selekcja logiczna

Dla arr = np.arange(1, 16) wybierz liczby: 
większe niż 5, ale mniejsze niż 10,
lub podzielne przez 3.
Połącz oba warunki operatorem logicznym | (OR). '''

arr = np.arange(1,16)
print("Pierwotna tablica: ", arr)
print("Liczby z przedziału (5,10): ", arr[((arr>5) & (arr<10)) | (arr %3 == 0)])

Pierwotna tablica:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Liczby z przedziału (5,10):  [ 3  6  7  8  9 12 15]


In [20]:
# 15. 

#  Utwórz tablicę np.arange(50).reshape(5,10) i wykonaj:
arr = np.arange(50).reshape(5,10)
print("Pierwotna tablica: \n", arr)

# wypisz pierwszy wiersz,
print("Pierwszy wiersz \n", arr[0, :])

# wypisz ostatnią kolumnę,
print("Ostatnia kolumna: \n", arr[:, -1])

# pobierz element z trzeciego wiersza i czwartej kolumny,
print(arr[2][3])

# pobierz submacierz 2x3 z prawego dolnego rogu.
print(arr[3:, 7:])

Pierwotna tablica: 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Pierwszy wiersz 
 [0 1 2 3 4 5 6 7 8 9]
Ostatnia kolumna: 
 [ 9 19 29 39 49]
23
[[37 38 39]
 [47 48 49]]


In [21]:
# 16. Statystyka w 2D

print("Pierwotna tablica: \n", arr)

# Dla tej samej tablicy oblicz:
# średnią w każdym wierszu (axis=1),
print("Średnia każdego wiersza w tablicy: ", arr.mean(axis=1))

#maksimum w każdej kolumnie (axis=0),
print("Maksimum z każdej kolumny: ", arr.max(axis=0))

#globalne minimum i maksimum.
print("Maksymalna wartość w tablicy: ", arr.max())
print("Minimalna wartość w tablicy: ", arr.min())

Pierwotna tablica: 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Średnia każdego wiersza w tablicy:  [ 4.5 14.5 24.5 34.5 44.5]
Maksimum z każdej kolumny:  [40 41 42 43 44 45 46 47 48 49]
Maksymalna wartość w tablicy:  49
Minimalna wartość w tablicy:  0


In [22]:
# 17. Warunki logiczne

print("Pierwotna tablica: \n", arr)
# Wybierz wszystkie elementy większe niż 30,
print("Elementy tablicy większe od 30: \n", arr[arr>30])

# Stwórz nową macierz zawierającą tylko te elementy,
arr_30 = arr[arr>30]
print("Nowa macierz: \n", arr_30)

# Zamień wszystkie wartości < 10 na 0.
arr_copy = arr.copy()  # Robimy to, żeby nie zmienić pierwotnej tablicy
arr_copy[arr_copy < 10] = 0
print("Po zmianie: \n", arr_copy)


Pierwotna tablica: 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Elementy tablicy większe od 30: 
 [31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Nowa macierz: 
 [31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Po zmianie: 
 [[ 0  0  0  0  0  0  0  0  0  0]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [23]:
# 18. Bonus — losowa macierz

# Wylosuj macierz np.random.randint(1,101, (4,4)),
arr = np.random.randint(1,101, (4,4))
print("Wylosowana macierz: \n", arr)

# Policz sumę w każdej kolumnie i w każdym wierszu,
print("Suma w każdej wierszu: \n", arr.sum(axis=1))
print("Suma w każdym kolumnie: \n", arr.sum(axis=0))


# Znajdź wartość maksymalną i jej współrzędne (wiersz, kolumna).
print("Wartość maksymalna w macierzy: \n", arr.max())

# Znajdź współrzędne (wiersz, kolumna) tej wartości
max_coords = np.unravel_index(np.argmax(arr), arr.shape) # np.argmax(arr) zwraca pozycję w wersji spłaszczonej (1D).
                                                         # np.unravel_index(..., arr.shape) przelicza ją na indeksy (wiersz, kolumna) w macierzy 2D.
print("Współrzędne maksymalnej wartości (wiersz, kolumna):", max_coords)

Wylosowana macierz: 
 [[54 12 82 85]
 [91 18 93 73]
 [25 59  6 94]
 [63 84 22 73]]
Suma w każdej wierszu: 
 [233 275 184 242]
Suma w każdym kolumnie: 
 [233 173 203 325]
Wartość maksymalna w macierzy: 
 94
Współrzędne maksymalnej wartości (wiersz, kolumna): (np.int64(2), np.int64(3))
